from __future__ import annotations

from .models import SourceDocument, Supplier


SUPPLIERS = [
    Supplier(
        id="nord-ingredients",
        name="Nord Ingredients",
        region="Europe",
        categories=["plant-protein", "nutrition"],
        certifications=["FSSC 22000", "ISO 22000"],
        min_order_quantity=500,
        unit_price_usd=5.8,
        lead_time_days=18,
        status="verified",
        source_document_ids=["doc-nord-cert", "doc-nord-quote"],
    ),
    Supplier(
        id="harbor-nutrition",
        name="Harbor Nutrition Labs",
        region="North America",
        categories=["plant-protein", "nutrition"],
        certifications=["FSSC 22000", "HACCP"],
        min_order_quantity=250,
        unit_price_usd=6.4,
        lead_time_days=12,
        status="verified",
        source_document_ids=["doc-harbor-assessment", "doc-harbor-quote"],
    ),
    Supplier(
        id="evergreen-trade",
        name="Evergreen Trade Co.",
        region="Asia",
        categories=["plant-protein", "sweetener"],
        certifications=["HACCP"],
        min_order_quantity=1_000,
        unit_price_usd=4.9,
        lead_time_days=28,
        status="lead",
        source_document_ids=["doc-evergreen-catalog"],
    ),
    Supplier(
        id="alpine-botanicals",
        name="Alpine Botanicals",
        region="Europe",
        categories=["botanicals", "nutrition"],
        certifications=["ISO 22000", "Organic EU"],
        min_order_quantity=300,
        unit_price_usd=8.1,
        lead_time_days=15,
        status="pending_review",
        source_document_ids=["doc-alpine-catalog", "doc-alpine-cert"],
    ),
]

DOCUMENTS = [
    SourceDocument(
        id="doc-nord-cert",
        title="Nord Ingredients FSSC 22000 certificate",
        source_type="certificate",
        supplier_id="nord-ingredients",
        excerpt="FSSC 22000 certificate for Nord Ingredients production site, valid through 2027-04-30.",
        authority="primary",
        updated_at="2026-06-01",
    ),
    SourceDocument(
        id="doc-nord-quote",
        title="Nord Ingredients Q2 demonstration quote",
        source_type="quote",
        supplier_id="nord-ingredients",
        excerpt="Demonstration quote: pea protein isolate, USD 5.80/kg, minimum order 500 kg, indicative lead time 18 days.",
        authority="supplier_provided",
        updated_at="2026-06-15",
    ),
    SourceDocument(
        id="doc-harbor-assessment",
        title="Harbor Nutrition Labs assessment",
        source_type="assessment",
        supplier_id="harbor-nutrition",
        excerpt="Internal demonstration assessment found an active FSSC 22000 certificate and complete allergen controls.",
        authority="internal",
        updated_at="2026-06-10",
    ),
    SourceDocument(
        id="doc-harbor-quote",
        title="Harbor Nutrition Labs Q2 demonstration quote",
        source_type="quote",
        supplier_id="harbor-nutrition",
        excerpt="Demonstration quote: pea protein isolate, USD 6.40/kg, minimum order 250 kg, indicative lead time 12 days.",
        authority="supplier_provided",
        updated_at="2026-06-18",
    ),
    SourceDocument(
        id="doc-evergreen-catalog",
        title="Evergreen Trade discovery catalog",
        source_type="catalog",
        supplier_id="evergreen-trade",
        excerpt="Third-party discovery catalog listing pea protein and sweetener products. No registration, audit, or inventory evidence attached.",
        authority="supplier_provided",
        updated_at="2026-05-20",
    ),
    SourceDocument(
        id="doc-alpine-catalog",
        title="Alpine Botanicals nutrition catalog",
        source_type="catalog",
        supplier_id="alpine-botanicals",
        excerpt="Nutrition and botanical extracts catalog. The plant protein line is not listed in this demonstration catalog.",
        authority="supplier_provided",
        updated_at="2026-05-12",
    ),
    SourceDocument(
        id="doc-alpine-cert",
        title="Alpine Botanicals organic certificate",
        source_type="certificate",
        supplier_id="alpine-botanicals",
        excerpt="Organic EU certificate is attached; an on-site quality review remains pending for this demonstration record.",
        authority="primary",
        updated_at="2026-04-10",
    ),
]
