"""内置演示样本数据集（合成数据）。

重要边界：以下全部商品、档口、报价、销量与证书均为演示用途的合成样本，
不代表任何真实商家，也不构成采购或上架建议。真实使用请通过
`POST /api/dataset/import` 或 `examples/dataset.example.json` 格式导入
自有货源资料（如平台 offer 页快照、报价单、质检资料）。
"""

from __future__ import annotations

from .models import EvidenceDocument, SourceProduct

PRODUCTS: list[SourceProduct] = [
    SourceProduct(
        id="phone-stand-1688-qiangda",
        platform="1688",
        title="铝合金桌面手机支架 直播补光款 多角度可调",
        category="手机支架",
        supplier="义乌强达数码配件商行",
        region="浙江金华",
        price_cny=3.2,
        market_ref_price_cny=12.9,
        min_order_qty=50,
        est_monthly_sales=3200,
        drop_ship_supported=True,
        image_count=8,
        status="verified",
        source_document_ids=["doc-phone-stand-qiangda-offer", "doc-phone-stand-qiangda-quote"],
    ),
    SourceProduct(
        id="phone-stand-pdd-jiali",
        platform="pdd-wholesale",
        title="通用桌面手机支架 折叠可调角度 支持一件代发",
        category="手机支架",
        supplier="揭阳佳力塑胶厂",
        region="广东揭阳",
        price_cny=2.6,
        market_ref_price_cny=12.9,
        min_order_qty=5,
        est_monthly_sales=8600,
        drop_ship_supported=True,
        image_count=6,
        status="verified",
        source_document_ids=["doc-phone-stand-jiali-offer", "doc-phone-stand-jiali-inspection"],
    ),
    SourceProduct(
        id="phone-stand-1688-xinyi",
        platform="1688",
        title="车载磁吸手机支架（档口线索，销量与资质未核验）",
        category="手机支架",
        supplier="深圳新意电子（线索档口）",
        region="广东深圳",
        price_cny=4.0,
        market_ref_price_cny=None,
        min_order_qty=100,
        est_monthly_sales=None,
        drop_ship_supported=False,
        image_count=3,
        status="lead",
        source_document_ids=["doc-phone-stand-xinyi-catalog"],
    ),
    SourceProduct(
        id="desk-organizer-1688-yueshi",
        platform="1688",
        title="抽屉式桌面收纳盒 亚克力透明 多规格",
        category="桌面收纳",
        supplier="台州悦时家居",
        region="浙江台州",
        price_cny=6.8,
        market_ref_price_cny=19.9,
        min_order_qty=24,
        est_monthly_sales=1500,
        drop_ship_supported=False,
        image_count=10,
        status="verified",
        source_document_ids=["doc-desk-organizer-yueshi-offer", "doc-desk-organizer-yueshi-quote"],
    ),
    SourceProduct(
        id="desk-organizer-yiwugo-mumu",
        platform="yiwugo",
        title="ins 风分层桌面收纳架 免安装 可一件代发",
        category="桌面收纳",
        supplier="义乌沐沐日用百货",
        region="浙江金华",
        price_cny=9.5,
        market_ref_price_cny=22.0,
        min_order_qty=1,
        est_monthly_sales=700,
        drop_ship_supported=True,
        image_count=12,
        status="pending_review",
        source_document_ids=["doc-desk-organizer-mumu-offer", "doc-desk-organizer-mumu-certificate"],
    ),
    SourceProduct(
        id="pet-toy-yiwugo-knot",
        platform="yiwugo",
        title="宠物绳结磨牙玩具 耐咬发声（目录线索，动销数据缺失）",
        category="宠物玩具",
        supplier="义乌宠趣用品（线索档口）",
        region="浙江金华",
        price_cny=1.9,
        market_ref_price_cny=None,
        min_order_qty=100,
        est_monthly_sales=None,
        drop_ship_supported=False,
        image_count=2,
        status="lead",
        source_document_ids=["doc-pet-toy-knot-catalog"],
    ),
]

DOCUMENTS: list[EvidenceDocument] = [
    EvidenceDocument(
        id="doc-phone-stand-qiangda-offer",
        product_id="phone-stand-1688-qiangda",
        source_type="offer",
        title="1688 offer 页快照：铝合金桌面手机支架",
        excerpt="offer 页快照：铝合金桌面手机支架，单件 3.20 元，起批 50 件，近 30 天成交 3200+，支持一件代发。",
        authority="platform",
        url="https://detail.1688.com/offer/example-0001.invalid",
        updated_at="2026-08-30",
    ),
    EvidenceDocument(
        id="doc-phone-stand-qiangda-quote",
        product_id="phone-stand-1688-qiangda",
        source_type="quote",
        title="档口报价单：强达数码配件商行",
        excerpt="演示报价单：3.20 元/件（50 件起），现货发浙江金华，代发加 0.5 元打包费。",
        authority="supplier_provided",
        url="",
        updated_at="2026-08-28",
    ),
    EvidenceDocument(
        id="doc-phone-stand-jiali-offer",
        product_id="phone-stand-pdd-jiali",
        source_type="offer",
        title="拼多多批发 offer 页快照：通用折叠手机支架",
        excerpt="offer 页快照：单件 2.60 元，5 件起批，近 30 天动销 8600+，标注一件代发与极速发货。",
        authority="platform",
        url="https://mobile.yangkeduo.com/example-0002.invalid",
        updated_at="2026-09-01",
    ),
    EvidenceDocument(
        id="doc-phone-stand-jiali-inspection",
        product_id="phone-stand-pdd-jiali",
        source_type="certificate",
        title="出厂抽检记录：佳力塑胶厂",
        excerpt="演示抽检记录：ABS 材质、折叠寿命 5000 次测试通过，附 2026-07 质检批次号。",
        authority="primary",
        url="",
        updated_at="2026-07-18",
    ),
    EvidenceDocument(
        id="doc-phone-stand-xinyi-catalog",
        product_id="phone-stand-1688-xinyi",
        source_type="offer",
        title="目录条目：新意电子车载磁吸支架",
        excerpt="仅目录收录条目：无主体资质、无成交与库存证据，档口核验未完成。",
        authority="platform",
        url="https://detail.1688.com/offer/example-0003.invalid",
        updated_at="2026-06-12",
    ),
    EvidenceDocument(
        id="doc-desk-organizer-yueshi-offer",
        product_id="desk-organizer-1688-yueshi",
        source_type="offer",
        title="1688 offer 页快照：抽屉式亚克力收纳盒",
        excerpt="offer 页快照：6.80 元/件，24 件起批，近 30 天成交 1500+，现货台州仓直发。",
        authority="platform",
        url="https://detail.1688.com/offer/example-0004.invalid",
        updated_at="2026-08-25",
    ),
    EvidenceDocument(
        id="doc-desk-organizer-yueshi-quote",
        product_id="desk-organizer-1688-yueshi",
        source_type="quote",
        title="档口报价单：台州悦时家居",
        excerpt="演示报价单：量大可议价（100 件以上 6.2 元/件），不含一件代发服务。",
        authority="supplier_provided",
        url="",
        updated_at="2026-08-22",
    ),
    EvidenceDocument(
        id="doc-desk-organizer-mumu-offer",
        product_id="desk-organizer-yiwugo-mumu",
        source_type="offer",
        title="义乌购 offer 页快照：ins 风分层收纳架",
        excerpt="offer 页快照：9.50 元/件，1 件起批，标注可代发，近 30 天动销 700+。",
        authority="platform",
        url="https://www.yiwugo.com/example-0005.invalid",
        updated_at="2026-08-29",
    ),
    EvidenceDocument(
        id="doc-desk-organizer-mumu-certificate",
        product_id="desk-organizer-yiwugo-mumu",
        source_type="certificate",
        title="材质安全说明：沐沐日用百货",
        excerpt="演示材质说明已附；档口现场人工复核尚未完成，状态暂不可标记为已验证。",
        authority="supplier_provided",
        url="",
        updated_at="2026-08-15",
    ),
    EvidenceDocument(
        id="doc-pet-toy-knot-catalog",
        product_id="pet-toy-yiwugo-knot",
        source_type="offer",
        title="目录条目：宠趣绳结磨牙玩具",
        excerpt="仅目录收录条目：无动销、无质检、无档口主体核验信息。",
        authority="platform",
        url="https://www.yiwugo.com/example-0006.invalid",
        updated_at="2026-05-30",
    ),
]


def build_dataset() -> tuple[list[SourceProduct], list[EvidenceDocument]]:
    """返回演示数据集的 (products, documents)。实际部署用 data_loader 替换。"""
    return list(PRODUCTS), list(DOCUMENTS)
